- lega/crypto.py
- lega/db.py
- lega/defaults.ini
- lega/utils.py
- lega/verify.py
- lega/worker.py
- logs/debug.yaml
- logs/main.yaml
- tools/db.sql
The verification step now uses the checksum of the final files, and not the decryption step anymore.
On the side, we now also capture (in the logs) the error messages from GPG.
Note: Not sure that PR is correct, since I tried to split it in 2. Well...we'll see if the reviewers understand.
> Adding the checksums for verification

- docker/entrypoints/connectors.sh
- docker/entrypoints/keys.sh
- docker/images/common/Dockerfile
- docker/images/db/Dockerfile
> Nj docker compose

- docker/images/Makefile
- docker/images/inbox/sshd_config
- terraform/instances/inbox/boot.tpl
I need to enable password auth (not just current "keyboard-interactive" auth) to use on CI server.
> Allow password authentication

- requirements.txt
Using SNYK to automate security test requires a manifest file. 
https://support.snyk.io/getting-started/languages-support
Create this file from the information in setup.py
> Create requirements.txt for SNYK

- docker/images/common/Dockerfile
Fix for https://github.com/NBISweden/LocalEGA/issues/156
> Fix pycryptodomex installation

- docker/ega.yml
- docker/entrypoints/inbox.sh
- docker/images/inbox/Dockerfile
- src/auth/Makefile
- src/auth/auth.conf.sample
- src/auth/backend.c
- src/auth/backend.h
- src/auth/blowfish/LINKS
- src/auth/blowfish/Makefile
- src/auth/blowfish/PERFORMANCE
- src/auth/blowfish/README
- src/auth/blowfish/crypt.3
- src/auth/blowfish/crypt.h
- src/auth/blowfish/crypt_blowfish.c
- src/auth/blowfish/crypt_blowfish.h
- src/auth/blowfish/crypt_gensalt.c
- src/auth/blowfish/crypt_gensalt.h
- src/auth/blowfish/glibc-2.1.3-crypt.diff
- src/auth/blowfish/glibc-2.14-crypt.diff
- src/auth/blowfish/glibc-2.3.6-crypt.diff
- src/auth/blowfish/ow-crypt.h
- src/auth/blowfish/wrapper.c
- src/auth/blowfish/x86.S
- src/auth/cega.c
- src/auth/config.c
- src/auth/config.h
Updating the C code to connect to Central EGA and not its fake instance.
We use a user/password combination for the moment, to make sure not everyone can query CentralEGA (over https).
The response is JSON formatted. We parse the response and query parts of it using `libjq`. Queries are parametrized in the `auth.conf` file. So is the REST endpoint and the user/password combination.
> Authentication against Central EGA's user database

- .travis.yml
Added integration between Travis CI and Slack.
> Add Slack notifications from Travis CI

- docker/bootstrap/cega.sh
Andreas recommended to not use `pushd`/`popd`
> Removing pushd/popd

- tests/src/test/java/se/nbis/lega/cucumber/Utils.java
- tests/src/test/java/se/nbis/lega/cucumber/hooks/BeforeAfterHooks.java
- tests/src/test/java/se/nbis/lega/cucumber/steps/Authentication.java
- tests/src/test/resources/cucumber/features/authentication.feature
The test is modified according to @silverdaz suggestion.
> Fix "database not available" user authentication test

- .gitignore
- deployments/docker/bootstrap/lib/instance.sh
- deployments/docker/ega.yml
- tests/README.md
> Integrate LocalEGA logging with Logstash

- deployments/docker/images/worker/Dockerfile.bootstrap
RPMs are not copied, there are downloaded from github (LFS)
> Updating the bootstrap image.

- .travis.yml
- tests/src/test/java/se/nbis/lega/cucumber/steps/Authentication.java
- tests/src/test/resources/simplelogger.properties
Fixed permissions issues in tests.
> Refactor tests, remove sudo

- extras/rpmbuild/RPMS/x86_64/gnupg-2.2.2-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/libassuan-2.4.3-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/libgcrypt-1.8.1-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/libgpg-error-1.27-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/libksba-1.3.5-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/ncurses-6.0-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/npth-1.5-1.el7.centos.x86_64.rpm
- extras/rpmbuild/RPMS/x86_64/pinentry-1.0.0-1.el7.centos.x86_64.rpm
- extras/rpmbuild/SOURCES/gnupg-2.2.2.tar.bz2
- extras/rpmbuild/SOURCES/libassuan-2.4.3.tar.bz2
- extras/rpmbuild/SOURCES/libgcrypt-1.8.1.tar.bz2
- extras/rpmbuild/SOURCES/libgpg-error-1.27.tar.bz2
- extras/rpmbuild/SOURCES/libksba-1.3.5.tar.bz2
- extras/rpmbuild/SOURCES/ncurses-6.0.tar.gz
- extras/rpmbuild/SOURCES/npth-1.5.tar.bz2
- extras/rpmbuild/SOURCES/pinentry-1.0.0.tar.bz2
Removed them in my vehemence. Now they're back.
> Added the git lfs files back

- README.md
- deployments/docker/Makefile
- docs/ingestion/db.rst
> Adding help to the makefile

- tests/src/test/resources/cucumber/features/authentication.feature
- tests/src/test/resources/cucumber/features/ingestion.feature
- tests/src/test/resources/cucumber/features/uploading.feature
In accordance with https://github.com/NBISweden/LocalEGA/wiki/Testing-LocalEGA
Authentication -> A.*
Uploading -> U.*
Data-In -> I.*
Data-Out -> O.*
> Change scenarios numeration naming and fix indentation

- extras/publish.py
- lega/ingest.py
- lega/openpgp/__main__.py
- lega/openpgp/packet.py
md5 assumed if the checksum algorithm is missing
I push in some unrelated commits too (about pgp)
> Some compatibility with CentralEGA

- deployments/docker/Makefile
- deployments/docker/bootstrap/instance.sh
- deployments/docker/bootstrap/settings/fin1
- deployments/docker/bootstrap/settings/swe1
Description: https://minio.io/
Tested with Python client: https://github.com/minio/minio-py
> Add Minio implementation of S3 to bootstrapping

- deployments/docker/README.md
- deployments/docker/images/Makefile
- deployments/docker/images/README.md
- docs/code.rst
- docs/conf.py
- docs/inbox.rst
- docs/index.rst
- docs/ingestion/encryption.rst
- docs/ingestion/overview.rst
- docs/setup.rst
- lega/conf/__init__.py
- lega/fs.py
- lega/ingest.py
- lega/keyserver.py
- lega/openpgp/__init__.py
- lega/utils/__init__.py
- lega/utils/amqp.py
- lega/utils/checksum.py
- lega/utils/crypto.py
- lega/utils/db.py
- lega/utils/eureka.py
- lega/utils/exceptions.py
- lega/utils/logging.py
- lega/vault.py
- lega/verify.py
These changes should have already been added and reviewed with https://github.com/NBISweden/LocalEGA/pull/266 but for some "reason" there are not visible.
> Add missing docs

- docs/connection.rst
- docs/static/lists/opensource-ads.txt
Probably not super nice, but maybe enough too (before the holidays)
> Message Format in the documentation

- deployments/docker/tests/src/test/java/se/nbis/lega/cucumber/Utils.java
- deployments/docker/tests/src/test/java/se/nbis/lega/cucumber/steps/Ingestion.java
- deployments/docker/tests/src/test/resources/config.properties
- deployments/docker/tests/src/test/resources/cucumber/features/ingestion.feature
Add I.10, I.13, and I.15 from https://github.com/NBISweden/LocalEGA/wiki/Testing-LocalEGA
> More integration tests

- .travis.yml
- deployments/docker/.gitignore
- deployments/docker/tests/src/test/java/se/nbis/lega/cucumber/CommonTests.java
- deployments/docker/tests/src/test/java/se/nbis/lega/cucumber/RobustnessTests.java
- deployments/docker/tests/src/test/java/se/nbis/lega/cucumber/Utils.java
- deployments/docker/tests/src/test/java/se/nbis/lega/cucumber/steps/Robustness.java
- deployments/docker/tests/src/test/resources/config.properties
- deployments/docker/tests/src/test/resources/cucumber/features/robustness.feature
Introduce "robustness" integration tests stage.
> Add "system restart" robustness test.

- deployments/docker/bootstrap/instance.sh
- deployments/docker/images/base/Dockerfile
- deployments/docker/images/inbox/Dockerfile
- deployments/docker/images/inbox/entrypoint.sh
- deployments/docker/images/vault/entrypoint.sh
- deployments/docker/images/worker/entrypoint.sh
- deployments/terraform/bootstrap/run.sh
> Add gosu permission deescalation
